core/core/urls.py
from django.contrib import admin
from django.urls import path, include
from drf_yasg.views import get_schema_view
from drf_yasg import openapi
from rest_framework import permissions

schema_view = get_schema_view(
    openapi.Info(
        title="Snippets API",
        default_version="v1",
        description="Test description",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="contact@snippets.local"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)
urlpatterns = [
    # Admin site URL
    path("admin/", admin.site.urls),
    # URLs for the accounts app
    path("accounts/", include("accounts.urls")),
    path("api-auth/", include("rest_framework.urls")),
    path(
        "swagger/",
        schema_view.with_ui("swagger", cache_timeout=0),
        name="schema-swagger-ui",
    ),
    path(
        "redoc/",
        schema_view.with_ui("redoc", cache_timeout=0),
        name="schema-redoc",
    ),
    # URLs for the todo app
    path("", include("todo.urls")),
]

core/todo/api/v1/urls.py
from django.urls import path
from .views import (
    TaskListViewSet,
    StatusListModuleSet,
    UsersListModuleSet,
    WeatherApi,
)
from rest_framework.routers import DefaultRouter

app_name = "api-v1"

router = DefaultRouter()
router.register("task", TaskListViewSet, basename="task")
router.register("status", StatusListModuleSet, basename="status")
router.register("users", UsersListModuleSet, basename="users")


urlpatterns = [
    path("weather/", WeatherApi.as_view(), name="weather"),
] + router.urls


"""urlpatterns = [
    path(
        "task/",
        TaskListViewSet.as_view({"get": "list", "post": "create"}),
        name="task-list",
    ),
    path(
        "status/",
        StatusListModuleSet.as_view({"get": "list", "post": "create"}),
        name="status-list",
    ),
    path(
        "task/<int:pk>/",
        TaskListViewSet.as_view(
            {
                "get": "retrieve",
                "put": "update",
                "patch": "partial_update",
                "delete": "destroy",
            }
        ),
        name="task-detail",
    ),
    path(
        "status/<int:pk>/",
        StatusListModuleSet.as_view(
            {
                "get": "retrieve",
                "put": "update",
                "patch": "partial_update",
                "delete": "destroy",
            }
        ),
        name="status-detail",
    ),
]"""

core/todo/urls.py
from django.urls import path, include
from todo.views import Tasklist, TaskCreate, DeleteView, TaskDone, TaskUpdate

# Set the app name for namespacing
app_name = "todo"

urlpatterns = [
    # Task list view
    path("", Tasklist.as_view(), name="task_list"),
    # Task create view
    path("create/", TaskCreate.as_view(), name="create_task"),
    # Task delete view
    path("delete/<int:pk>/", DeleteView.as_view(), name="delete_task"),
    # Task done view
    path("done/<int:pk>/", TaskDone.as_view(), name="done_task"),
    # Task update view
    path("edit/<int:pk>/", TaskUpdate.as_view(), name="update_task"),
    path("api/v1/", include("todo.api.v1.urls")),
]

core/todo/models.py
from django.db import models

# from django.urls import reverse


class Status(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name


# Create your models here.
class Task(models.Model):
    # ForeignKey relationship with User model
    # user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    author = models.ForeignKey(
        "accounts.Profile",
        on_delete=models.SET_NULL,
        null=True,
        related_name="posts_author",
    )
    # Title field for the task
    title = models.CharField(max_length=200)
    description = models.TextField()
    # Status field to indicate if the task is complete or not
    status = models.ForeignKey(
        "Status", on_delete=models.SET_NULL, null=True, blank=True
    )

    # Created date field to store the date and time of task creation
    created_date = models.DateTimeField(auto_now_add=True)

    # Updated date field to store the date and time of task update
    updated_date = models.DateTimeField(auto_now=True)

    class Meta:
        # Specify the order of tasks with respect to the user
        order_with_respect_to = "created_date"

    def __str__(self):
        return self.title

    def get_snippet(self):
        return self.description[0:5]

core/todo/forms.py
from django import forms
from todo.models import Task


# Task form for creating new tasks
class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ("title", "description", "status")

core/todo/api/v1/views.py
from rest_framework.permissions import IsAuthenticated
from rest_framework import viewsets
from django_filters.rest_framework import DjangoFilterBackend
from rest_framework.filters import SearchFilter, OrderingFilter
from django.views.decorators.cache import cache_page
from django.utils.decorators import method_decorator
import requests
from django.http import JsonResponse
from django.views import View
from .serializers import Taskserializers, Statusserializers, Usersserializers
from .pagination import CustomPagination
from .permissions import IsOwnerOrReadOnly
from accounts.models import User
from todo.models import Task, Status


class TaskListViewSet(viewsets.ModelViewSet):
    permission_classes = [IsAuthenticated, IsOwnerOrReadOnly]
    serializer_class = Taskserializers
    queryset = Task.objects.all()
    filter_backends = [DjangoFilterBackend, SearchFilter, OrderingFilter]
    filterset_fields = {
        "author": ["exact", "in"],
        "status": ["exact", "in"],
    }
    search_fields = ["=title", "description"]
    ordering_fields = ["created_date"]
    pagination_class = CustomPagination

    @method_decorator(cache_page(60 * 5))  # Cache for 5 minutes
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)


class StatusListModuleSet(viewsets.ModelViewSet):
    permission_classes = [IsAuthenticated]
    serializer_class = Statusserializers
    queryset = Status.objects.all()


class UsersListModuleSet(viewsets.ModelViewSet):
    permission_classes = [IsAuthenticated]
    serializer_class = Usersserializers
    queryset = User.objects.all()


class WeatherApi(View):
    def get(self, request, *args, **kwargs):
        url = "https://api.openweathermap.org/data/2.5/weather"
        params = {
            "q": "Tehran",  # Replace with the desired city name
            "appid": "23db3c61c5a56bdcb6c098685539fdf8",
        }
        response = requests.get(url, params=params)
        data = response.json()

        return JsonResponse(
            data
        )  # Convert data to JsonResponse and return it

    @method_decorator(cache_page(60 * 20))  # Cache for 5 minutes
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)


"""class TaskListViewSet(viewsets.ViewSet):
    #permission_classes =[IsAuthenticated]
    serializer_class = Taskserializers
    queryset = Task.objects.all()
    def list(self, request):
        serializer = self.serializer_class(Task.objects.all(), many=True)
        return Response(serializer.data)
    def retrieve(self, request, pk=None):
        task_object = get_object_or_404(self.queryset, pk=pk)
        serializer = self.serializer_class(task_object)
        return Response(serializer.data)
    def create(self, request):
        serializer = self.serializer_class(data=request.data)
        serializer.is_valid(raise_exception=True)
        serializer.save()
        return Response(serializer.data)
    def update(self, request, pk=None):
        task_object = get_object_or_404(self.queryset, pk=pk)
        serializer = self.serializer_class(task_object, data=request.data)
        serializer.is_valid(raise_exception=True)
        serializer.save()
        return Response(serializer.data)
    def partial_update(self, request, pk=None):
        pass
    def destroy(self, request, pk=None):
        task_object = get_object_or_404(self.queryset, pk=pk)
        task_object.delete()
        return Response({'detail': "Item removed successfully"},
        status=status.HTTP_204_NO_CONTENT)
"""

core/todo/views.py
from django.shortcuts import redirect, get_object_or_404
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.detail import DetailView
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from todo.models import Task, Status
import time
from django.views.decorators.cache import cache_page
from django.utils.decorators import method_decorator


@method_decorator(cache_page(60 * 30), name="dispatch")
class Tasklist(LoginRequiredMixin, ListView):
    model = Task
    context_object_name = "tasks"
    template_name = "todo/list_task.html"

    def get_queryset(self):
        time.sleep(10)
        return self.model.objects.filter(author=self.request.user.id)


class TaskCreate(LoginRequiredMixin, CreateView):
    model = Task
    fields = ["title", "description", "status"]
    success_url = reverse_lazy("todo:task_list")

    def form_valid(self, form):
        form.instance.author_id = self.request.user.id
        return super(TaskCreate, self).form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["tasks"] = Status.objects.all()
        return context


class DeleteView(LoginRequiredMixin, DeleteView):
    model = Task
    context_object_name = "task"
    success_url = reverse_lazy("todo:task_list")


class TaskDone(LoginRequiredMixin, DetailView):
    model = Task
    context_object_name = "task"
    success_url = reverse_lazy("todo:task_list")

    def get(self, request, pk):
        task = get_object_or_404(Task, pk=pk)
        if task.status != "completed":
            task.status = get_object_or_404(Status, name="Completed")
            task.save()
        return redirect("todo:task_list")


class TaskUpdate(LoginRequiredMixin, UpdateView):
    template_name_suffix = "_update"
    model = Task
    fields = ["title", "description", "status"]
    success_url = reverse_lazy("todo:task_list")

    def form_valid(self, form):
        return super(TaskUpdate, self).form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["tasks"] = Status.objects.all()
        return context

core/todo/templates/todo/task_confirm_delete.html
{% extends 'base.html' %}

{% block title %} Delete Task {% endblock %}


{% block content %}
  <div class="container mt-4">
    <h1>Delete Task</h1>
    <p>Are you sure you want to delete this task?</p>
    <form method="post">
      {% csrf_token %}
      <div class="form-group">
        <label for="taskName">Task Name</label>
        <input type="text" class="form-control" id="taskName" value="{{task.title}}" disabled>
      </div>
      <div class="form-group">
        <label for="taskDescription">Task Description</label>
        <textarea class="form-control" id="taskDescription" rows="3" disabled>{{task.description}}</textarea>
      </div>
      <div class="form-group">
        <label for="taskStatus">Task Status</label>
        <input type="text" class="form-control" id="taskStatus" value="{{task.status}}"  disabled>
      </div>
      <button type="submit" class="btn btn-danger">Delete Task</button>
    </form>
  </div>
  {% endblock %}

core/todo/templates/todo/task_form.html
{% extends 'base.html' %}

{% block title %} Create Task {% endblock %}


{% block content %}
  <div class="container mt-4">
    <h1>Create Task</h1>
    <form method="post" action="{% url 'todo:create_task' %}">
      {% csrf_token %}
      <div class="form-group">
        <label for="taskName">Task Name</label>
        <input type="text" class="form-control" name="title" placeholder="Enter task name">
      </div>
      <div class="form-group">
        <label for="taskDescription">Task Description</label>
        <textarea class="form-control" name="description" rows="3" placeholder="Enter task description"></textarea>
      </div>
      <div class="form-group">
        <label  id="status">Task Status</label>
        <select class="form-control" name="status" >
          <option value="">--Please choose an status--</option>
          {% for task in tasks %}
          <option value="{{task.id}}" name="status" >{{task.name}}</option>
          {% endfor %}
        </select>
      </div>
      <button type="submit" class="btn btn-primary">Create Task</button>
    </form>
  </div>
  {% endblock %}

core/todo/templates/todo/task_list.html
{% extends 'base.html' %}

{% block title %} Todo Task {% endblock %}


{% block content %}
  <div class="container mt-4">
    <h1>Add Task</h1>
    <form method="post" action="{% url 'todo:create_task' %}">
      {% csrf_token %}
      <button type="submit" class="btn btn-primary">Add Task</button>
    </form>
  </div>
  
  <div class="container mt-4">
    <h1>My Tasks</h1>
    <table class="table">
      <thead>
        <tr>
          <th>Task Name</th>
          <th>Task Description</th>
          <th>Task Status</th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody>
        {% for task in tasks %}
        <tr>
          {% if task.status.name == 'Completed' %}
          <td><strike>{{task.title}}</strike></td>
          <td><strike>{{task.description}}</strike></td>
          {% else %}
          <td>{{task.title}}</td>
          <td>{{task.description}}</td>
          {% endif %}
          
          <td>{{task.status}}</td>
          <td>
            <a href="{% url 'todo:update_task' task.id %}"><button class="btn btn-primary">Edit</button></a>
            <a href="{% url 'todo:delete_task' task.id %}"><button class="btn btn-danger">Delete</button></a>
            <a href="{% url 'todo:done_task' task.id %}"><button class="btn btn-success">Done</button></a>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
  {% endblock %}

core/todo/templates/todo/task_update.html
{% extends 'base.html' %}

{% block title %} Update Task {% endblock %}


{% block content %}

  <div class="container">
    <h1>Update Task</h1>
    <form method="post" action="{% url 'todo:update_task' task.id %}">
      {% csrf_token %}
      <div class="form-group">
        <label for="taskName">Task Name</label>
        <input type="text" class="form-control" name="title" value="{{task.title}}" placeholder="Enter task name">
      </div>
      <div class="form-group">
        <label for="taskDescription">Task Description</label>
        <textarea class="form-control" name="description" rows="3" >{{task.description}}</textarea>
      </div>
      <div class="form-group">
        <label  id="status">Task Status</label>
        <select class="form-control" name="status">
          {% for obj in tasks %}
          {% if obj.id == task.status_id %}
          <option value="{{obj.id}}" name="status" selected >{{obj.name}}</option>
          {% else %}
          <option value="{{obj.id}}" name="status" >{{obj.name}}</option>
          {% endif %}
          {% endfor %}
        </select>
      </div>
      <button type="submit" class="btn btn-primary">Update Task</button>
    </form>
  </div>
  {% endblock %}